services:
  # --- Service 1: Database (PostgreSQL) ---
  db:
    image: postgres:15
    container_name: tubes_db
    restart: always
    environment:
      POSTGRES_DB: tubes_db
      POSTGRES_USER: tubes_user
      POSTGRES_PASSWORD: tubes_password
    volumes:
      - ./db-data:/var/lib/postgresql/data
    # ports:             
    #   - "5435:5432"
    networks:
      - tubes_net

  # --- Service 2: Backend (Laravel) ---
  backend:
    build:
      context: ./backend-api
      dockerfile: Dockerfile
    container_name: tubes_backend
    restart: always
    working_dir: /var/www/html
    volumes:
      - ./backend-api:/var/www/html
    ports:
      - "8082:8000"      # Aman
    depends_on:
      - db
    networks:
      - tubes_net

  # --- Service 3: Frontend (React) ---
  frontend:
    build:
      context: ./frontend-web
      dockerfile: Dockerfile
    container_name: tubes_frontend
    restart: always
    ports:
      - "8081:80"        # Aman
    depends_on:
      - backend
    networks:
      - tubes_net

  prometheus:
    image: prom/prometheus:latest
    container_name: tubes_prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"      # Aman
    networks:
      - tubes_net

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: tubes_cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - "8084:8080"
    networks:
      - tubes_net

  grafana:
    image: grafana/grafana:latest
    container_name: tubes_grafana
    ports:
      - "3001:3000"      # Aman
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - tubes_net
    depends_on:
      - prometheus

networks:
  tubes_net:
    driver: bridge