services:
  # --- Service 1: Database (PostgreSQL) ---
  db:
    image: postgres:15
    container_name: tubes_db       # Nama Baru
    restart: always
    environment:
      POSTGRES_DB: tubes_db        # Nama DB Baru
      POSTGRES_USER: tubes_user    # User Baru
      POSTGRES_PASSWORD: tubes_password # Password Baru
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      - "5435:5432"               # Port Aman
    networks:
      - tubes_net

  # --- Service 2: Backend (Laravel) ---
  backend:
    build:
      context: ./backend-api
      dockerfile: Dockerfile
    container_name: tubes_backend  # Nama Baru
    restart: always
    working_dir: /var/www/html
    volumes:
      - ./backend-api:/var/www/html
    ports:
      - "8082:8000"               # Port Aman
    depends_on:
      - db
    networks:
      - tubes_net

  # --- Service 3: Frontend (React) ---
  frontend:
    build:
      context: ./frontend-web
      dockerfile: Dockerfile
    container_name: tubes_frontend # Nama Baru
    restart: always
    ports:
      - "8081:80"                 # Port Aman
    depends_on:
      - backend
    networks:
      - tubes_net

networks:
  tubes_net:
    driver: bridge