name: CI Tubes IPA (Laravel + React)

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  laravel-test:
    name: Backend Test (Laravel)
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./backend-api

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.4' 
        extensions: mbstring, dom, fileinfo, mysql
    
    - name: Copy .env
      run: cp .env.example .env

    - name: Install Dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Generate Application Key
      run: php artisan key:generate

    - name: Run Tests (PHPUnit)
      run: php artisan test

  react-build:
    name: Frontend Build (React)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend-web

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Dependencies
      run: npm install

    - name: Check Linting (Opsional)
      run: echo "Linting dilewati dulu..." # SAYA TAMBAHKAN INI AGAR TIDAK ERROR

    - name: Run Build
      run: npm run build

    - name: Run Tests
      run: npm test -- --watchAll=false