name: CI/CD Tubes IPA (Laravel + React)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: 

jobs:
  # 1. TEST BACKEND
  laravel-test:
    name: Backend Test (Laravel)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend-api

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.4'
        extensions: mbstring, dom, fileinfo, mysql
    
    - name: Copy .env
      run: cp .env.example .env

    - name: Install Dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Generate Application Key
      run: php artisan key:generate

    - name: Run Tests (PHPUnit)
      run: php artisan test

  # 2. BUILD FRONTEND
  react-build:
    name: Frontend Build (React)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend-web

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Dependencies
      run: npm install

    - name: Check Linting (Skip)
      run: echo "Linting dilewati..."

    - name: Run Build
      run: CI=false npm run build

  # 3. DEPLOY KE VPS (Hanya jalan kalau Test & Build sukses)
  deploy:
    name: ðŸš€ Auto Deploy to VPS
    runs-on: ubuntu-latest
    
    needs: [laravel-test, react-build]
    
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: 22
          script: |
            # Masuk ke folder project
            cd ${{ secrets.PROJECT_PATH }}
            
            # 1. Ambil kodingan terbaru
            git pull origin main
            
            # 2. Paksa Build Frontend tanpa cache (Biar teks pasti berubah)
            # Pastikan nama service di docker-compose.yml adalah 'frontend'
            sudo docker compose build --no-cache frontend
            
            # 3. Build & Restart sisanya
            sudo docker compose up -d --build
            
            # 4. Bersihkan sampah
            sudo docker system prune -f